### ISSUE TITLE
3D model movement on Google WebGL maps

### ISSUE THREAD

**Issue by gireeshbhogireddy** [googlecodelabs/maps-platform-101-webgl#1]
Can I have the sample code of how the airplane gltf model moving on google maps with 3D buildings

https://geo-devrel-io2021-travel.web.app/#flights

**Comment by i4innovationnet** [comment]
This was marked as completed but I couldn't find the source code for the demo. I'm also looking to add floating place labels like these but couldn't find how to achieve it. 

![Image](https://github.com/user-attachments/assets/5fe1c584-43f1-45b4-b382-d38b32ad1fee)
