### ISSUE TITLE
Error showing code in the Documentation

### ISSUE THREAD

**Issue by zeser78** [googlecodelabs/maps-platform-101-webgl#6]
In this section https://developers.google.com/codelabs/maps-platform/webgl#3, it has a mistake showing the function initWebGLOverlayView(map) but it's WebglOverlayView() and inside this function ` webglOverlayView.onContextRestored = ({gl}) => {}` and  `webglOverlayView.onDraw = ({gl, coordinateTransformer}) => {}`, the parameters are without curly parentheses.

And here: https://developers.google.com/codelabs/maps-platform/webgl#5 , you use the parameter `transformer`, but in the rest of the documentation and sample code use ` coordinateTransformer`.

**Comment by zeser78** [comment]
Different name in Doc and Code in the `initWebGLOverlayView()` and `initWebglOverlayView()` function.

**Comment by amuramoto** [comment]
Fix incoming. Thanks!
