### ISSUE TITLE
infinit ondraw

### ISSUE THREAD

**Issue by dotku** [googlecodelabs/maps-platform-101-webgl#8]
![image](https://user-images.githubusercontent.com/1519232/163897506-5842996e-538c-4a2f-a7e5-c52b2528f093.png)

I found that webGLOverlayView.onDraw will run infinitely, anyway we can stop it if there is no movement?

**Comment by amuramoto** [comment]
This codelab is meant to run infinitely. If you want to stop, you can set a conditional to stop recursively calling `requestAnimationFrame`
